### ISSUE TITLE
超星建议不要把明文账号密码写进去

### ISSUE THREAD

**Issue by daofeng2015** [King-1025/Gaction#1]
看了下,好像把登录账号的明文和密码直接写到py文件里了,要是能出个文档说明就更好了!!!

**Comment by King-Test** [comment]
超星的那个是公共测试账号，可以拿去用，云盘上传主要用的是科研在线，但是今年六月份的时候，科研在线被封了！这个仓库现在是自己开发用，文档的话请访问这个仓库：https://github.com/King-Test/Gaction/blob/master/INSTALL.md

**Comment by King-1025** [comment]
哈哈，谢谢😊，超星的那个是测试账号，可以拿去用，云盘上传原来用的是科研在线，但是今年六月份的时候，某些东西的鼻子狗灵狗灵的，科研在线被封了！后来，这个仓库增加了超星上传，一直是自己在用。文档请访问这个老仓库：https://github.com/King-Test/Gaction/blob/master/INSTALL.md，但是，这个仓库现在并不支持超星上传，后面也许会加进去吧。




---原始邮件---
发件人: "蒋"<notifications@github.com&gt;
发送时间: 2020年8月14日(周五) 晚上9:23
收件人: "King-1025/Gaction"<Gaction@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [King-1025/Gaction] 超星建议不要把明文账号密码写进去 (#1)




 
看了下,好像把登录账号的明文和密码直接写到py文件里了,要是能出个文档说明就更好了!!!

**Comment by daofeng2015** [comment]
> 哈哈，谢谢😊，超星的那个是测试账号，可以拿去用，云盘上传原来用的是科研在线，但是今年六月份的时候，某些东西的鼻子狗灵狗灵的，科研在线被封了！后来，这个仓库增加了超星上传，一直是自己在用。文档请访问这个老仓库：[https://github.com/King-Test/Gaction/blob/master/INSTALL.md，但是，这个仓库现在并不支持超星上传，后面也许会加进去吧。](https://github.com/King-Test/Gaction/blob/master/INSTALL.md%EF%BC%8C%E4%BD%86%E6%98%AF%EF%BC%8C%E8%BF%99%E4%B8%AA%E4%BB%93%E5%BA%93%E7%8E%B0%E5%9C%A8%E5%B9%B6%E4%B8%8D%E6%94%AF%E6%8C%81%E8%B6%85%E6%98%9F%E4%B8%8A%E4%BC%A0%EF%BC%8C%E5%90%8E%E9%9D%A2%E4%B9%9F%E8%AE%B8%E4%BC%9A%E5%8A%A0%E8%BF%9B%E5%8E%BB%E5%90%A7%E3%80%82)
> […](#)
> ---原始邮件--- 发件人: "蒋"<notifications@github.com&gt; 发送时间: 2020年8月14日(周五) 晚上9:23 收件人: "King-1025/Gaction"<Gaction@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [King-1025/Gaction] 超星建议不要把明文账号密码写进去 (#1) 看了下,好像把登录账号的明文和密码直接写到py文件里了,要是能出个文档说明就更好了!!! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你最好那段文字写到链接里面了....能否给代码写上注释就行了.基础用法一看就知道.主要是参数不知道传啥

**Comment by King-1025** [comment]
你想传啥参数呀？原来的仓库，我已经加入“超星云盘”了，[请点击查看](https://github.com/King-Test/Gaction)。如果，云盘再被封的话，俺已经懒得维护了。< ́;︵;̀ >

Gaction的核心：就是在github actions虚拟环境中，下载墙外资源后，再上传到墙内的某个网盘或者存储位置。

由于，GFW几乎不可能限制虚拟环境访问墙外资源，所以，Gaction可以实现访问墙外资源的目的。对于墙内的存储位置，你可以自己搭建网盘的。有兴趣的话，可以自己搞啊，也不一定要用github actions，类似提供“持续集成服务”的免费平台都可以，比如：azure、travis等等。
